name:                bp-servant-polysemy-todo-app
version:             0.1.0.0
github:              "https://github.com/rabbitonweb/bp-servant-polysemy-todo-ap"
license:             BSD3
author:              "Pawel Szulc (AskBlackRabbit)"
maintainer:          "paul.szulc@gmail.com"
copyright:           "2019 Pawel Szulc"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/rabbitonweb/bp-servant-polysemy-todo-ap>

default-extensions:
- DeriveGeneric

dependencies:
- base >= 4.7 && < 5
- text
- aeson

library:
  source-dirs: src

executables:
  app:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bp-servant-polysemy-todo-app

tests:
  unit-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bp-servant-polysemy-todo-app
    - hspec
